spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chat
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
example:
  jwtSecret: secret
  jwtExpirationMs: 86400000
  jwtRefreshExpirationDateInMs: 9000000
