spring:
  datasource:
    url: jdbc:mariadb://localhost:3306/chat
    username: root
    password:
  jpa:
    hibernate:
      ddl-auto: update
    generate-ddl: true

example:
  jwtSecret: secret
  jwtExpirationMs: 108000000
  jwtRefreshExpirationDateInMs: 109000000
